name: Docker Image CI for version 7.9

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 1'

env:
  DOCKER_IMAGE_CONTEXT_PATH: 7.9/debian/default/
  DOCKERHUB_IMAGE_TAGS: |
    nicoherbigde/sonarsource-sonarqube:7.9
    nicoherbigio/sonarsource-sonarqube:7.9
    nicoherbigde/sonarsource-sonarqube:7.9.6
    nicoherbigio/sonarsource-sonarqube:7.9.6

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image and Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKER_IMAGE_CONTEXT_PATH }}
          push: true
          tags: ${{ env.DOCKERHUB_IMAGE_TAGS }}
